[package]
name = "elasticsearch_exporter"
version = "0.16.0"
authors = ["Ernestas Poskus <ernestas@vinted.com>"]
edition = "2018"
description = """
Vinted Elasticsearch exporter
"""
documentation = "https://docs.rs/elasticsearch_exporter"
homepage = "https://github.com/vinted/elasticsearch-exporter-rs"
license = "MIT"
repository = "https://github.com/vinted/elasticsearch-exporter-rs"
autobins = false

[[bin]]
name = "elasticsearch_exporter"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
elasticsearch = { version = "7.11.0-alpha.1", features = ["rustls-tls"], default-features = false }
prometheus = { version = "0.12.0", default-features = false, features = ["process", "protobuf"] }
serde = "1.0.124"
serde_json = "1.0.64"
lazy_static = "1.4.0"
clap = { version = "3.0.0-beta.2", default-features = false, features = ["suggestions", "color", "derive", "std", "cargo"] }
log = "0.4.14"
pretty_env_logger = "0.4.0"
url = "2.2.1"
humantime = "2.1.0"
serde_derive = "1.0.124"
serde_qs = "0.8.3"
byte-unit = "4.0.9"
oorandom = "11.1.3"

[dependencies.hyper]
version = "0.14.4"
default-features = false
features = ["runtime", "tcp", "server"]

[dependencies.tokio]
version = "1.3.0"
default-features = false
features = ["rt-multi-thread", "signal", "sync", "macros", "time"]
